---
title: "500-series Streetcar Lines Experienced Most Delays in 2023"
author: "Talia Fabregas"
date: "January 21, 2024"
format: pdf
editor: visual
---

## Abstract

TTC Streetcar Delay Data from Open Data Toronto.

## Contents

1.  Introduction

2.  Data

    1.  Data Collection

    2.  Data Processing

    3.  Ethical Considerations

3.  Conclusions

4.  References

5.  References

## Introduction

## Data

```{r}
#| include: false
#| warning: false
#| message: false
library(tidyverse)
library(opendatatoronto)
library(janitor)
library(dplyr)
library(ggplot2)
```

## 

```{r}
#| label: fig-delaysperline
#| fig-cap: Total Delays Per TTC Streetcar Line, 2023
#| echo: false
#| warning: false
#| message: false
streetcar_data <- read_csv(here::here("outputs/data/streetcar_data.csv"))

delays_per_line <- streetcar_data %>%
  group_by(streetcar_line) %>%
  summarize(delay_count = n())


```

```{r}
#| label: fig-rushhourdelays
#| fig-cap: Total Delays Per TTC Streetcar Line at Rush Hour, 2023
#| echo: false
#| warning: false
#| message: false

```

## Conclusions

## References
